name: upload ghpages to S3(manual)
on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'AWS S3 Bucket Name'
        required: true
        default: 'static.asmatrix.com'
      bucket_region:
        description: 'AWS Region(ap-eastnorth-1,us-east-1)'
        required: true
        default: 'ap-east-1'
      bucket_dir:
        description: 'Bucket Directory(eg. site-docu,defaults to the root of the bucket.)'
        required: false
        default: 'site-asmatrix'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    env: 
      REPO: static.asmatrix.com

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master    

      - name: sync mkdocs-desktop to mydocu
        run: |
          echo "PWD: ${PWD}"
          ls -al -h
          git clone git@github.com:huhongjun/mkdocs-asmatrix.git
          cp mkdocs-desktp
          
